### ISSUE TITLE
Support for Kimai 2.0.0

### ISSUE THREAD

**Issue by jensschaerer** [glorpen/kimai-duration-plugin#2]
Are there any plans this plugin will support Kimai 2.0.0 and up?

**Comment by glorpen** [comment]
I don't foresee any technical problems with it so it is only question of free time. I'll probably get to it somewhere in next week.

**Comment by kevinpapst** [comment]
@glorpen can I update the store page?
https://www.kimai.org/store/glorpen-duration-bundle.html
<img width="509" alt="Bildschirmfoto 2023-06-09 um 19 02 32" src="https://github.com/glorpen/kimai-duration-plugin/assets/533162/a747331e-99ed-4c46-bce5-43b9176dbf8e">

**Comment by glorpen** [comment]
@kevinpapst yes, please. thanks!
